dist: xenial
sudo: false
language: python
install: pip install tox
env:
  - HYPOTHESIS_PROFILE=ci
jobs:
  include:
    - python: 3.7
      name: "Python 3.7"
      dist: xenial
      sudo: true
      script: tox -e py37
    - python: 3.7
      name: "Coverage"
      dist: xenial
      sudo: true
      script: tox -e coverage
    - python: 3.7
      name: "Bandit"
      dist: xenial
      sudo: true
      script: tox -e bandit
    - python: 3.6
      name: "Python 3.6"
      dist: xenial
      sudo: true
      script: tox -e py36
branches:
  only:
  - master
